#!/bin/bash

echo "=== Deploy Backend to GitHub & Railway ==="
echo ""
echo "Step 1: Create GitHub Repository"
echo "  1. Go to: https://github.com/new"
echo "  2. Repository name: gold-price-backend"
echo "  3. Keep it Private (recommended)"
echo "  4. Don't check 'Add a README'"
echo "  5. Click 'Create repository'"
echo ""
read -p "Press Enter after creating the GitHub repository..."

echo ""
echo "Step 2: Add GitHub Remote"
echo "  Replace YOUR_USERNAME with your actual GitHub username:"
echo ""
echo "  git remote add origin https://github.com/YOUR_USERNAME/gold-price-backend.git"
echo ""
read -p "Press Enter after adding the remote..."

echo ""
echo "Step 3: Push to GitHub"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""
read -p "Press Enter after pushing to GitHub..."

echo ""
echo "=== Next Steps ==="
echo "1. Go to https://railway.app"
echo "2. Sign in with GitHub"
echo "3. Click 'New Project' → 'Deploy from GitHub repo'"
echo "4. Select 'gold-price-backend'"
echo "5. Click 'Deploy Now'"
echo ""
echo "Wait 2-3 minutes for deployment..."
echo "Then copy your Railway URL and update Flutter app!"
echo ""
